### ISSUE TITLE
[UMBRELLA] Plots: more functions

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#312]
We aim at increasing the flexibility and functionality of Health-GPS plots in terms of

- [ ] choosing the version of Health-GPS which affects the name of variables
- [ ] #314
- [ ] #315
- [ ] choosing to summarize the variables or not
- [ ] choosing to compare the data with calculations (and export results) or not

Meanwhile, 

- [ ] README needs to be elaborated and more granular.
