### ISSUE TITLE
[UMBRELLA] Overhaul of input data backend

### ISSUE THREAD

**Issue by dalonsoa** [imperialCHEPI/healthgps#357]
(@dalonsoa dumping here stuff)

- [ ] Identify where default values are assigned silently and make the program fail or raise a warning
- [ ] Validate input information - eg. type, ranges, etc. in all information in input files - and make the program fail if invalid
- [ ] Identify suspicious changes - like clamping negative values, etc. - and raise a warning

Use meaningful and informative messages in all cases

**Comment by jamesturner246** [comment]
Assigning @alexdewar, but the description needs updating after discussion. Will do so shortly..

**Comment by alexdewar** [comment]
I think this is a good starting point.

I've opened an issue specifically for validating the `index.json` file (#360) for starters, because a) we have to start somewhere :stuck_out_tongue:  and b) we *could* validate it using a JSON schema, which I want to try doing for HealthGPS. If the approach turns out to be useful, we could extend it to other input files.

CSV files are unfortunately another story, but we can worry about that later :wink:

**Comment by jamesturner246** [comment]
I think this is now redundant, and covered by other issues.

Closing.
