### ISSUE TITLE
Add time trend in risk factors

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#477]
We are adding an underlying time trend in risk factors from consuming UPF (ultra-processed food).
The plan is to add time (or year) as an additional variable into risk factor equations.

- [x] The parameters need to be estimated.
- [x] It needs to be confirmed how this time trend will affect other equations in Health-GPS.
- [x] #492 
- [x] #493

**Comment by jzhu20** [comment]
Details on estimating time trend parameters from Jingmin:

- With time trend parameters provided for each individual in Maxime's data, time trend parameters will be estimated on gender, age, sector, income, baseline nutrients before time trend (carbohydrate, fat, protein, sodium) to add to HealthGPS.

Steps from James:

1. update base nutrients as before
2. compute and add a delta for the time trend, based on base nutrients and income, sector, etcetera
3. do clipped expected value adjustment as before
4. do clipped policy update as before

**Comment by jzhu20** [comment]
Jingmin needs to confirm:

- [ ] Whether factors mean of nutrients needs to be updated or not
- [ ] Whether policy parameters need to be updated or not, since baseline nutrients are adjusted with time trend now

**Comment by jzhu20** [comment]
Update on applying time factor:

Everyone in the virtual population is assigned a time factor for each nutrient based on age, gender, income, sector and nutrient levels. This individual-specific time factor remains constant over life course. At each year step, nutrient intake needs to multiply the individual-specific time factor.

**Comment by jzhu20** [comment]
Estimating time factor as a function of age, sex, income, sector, and baseline nutrient intake.

- Filter is 0
- No smoothing on time factors
- **X**: sex, age1, age2, age3, sector, income tertile, log_carb, log_fat, log_protein, log_sodium

**Comment by jzhu20** [comment]
Factors mean is adjusted with a fixed time factor _r_, i.e., Adjusted mean = mean * _r<sup>T</sup>_.

Time factor is 

- 1.00425 for Carbohydrate;
- 1.0122 for Fat;
- 1.00452 for Protein;
- 1.00392 for Sodium.

Mean weight adjustment happens after nutrients intake is adjusted with time trend.

For a certain age, gender group,
_mean weight = 0.06256 * mean time-trend-adjusted-Energy Intake - 0.6256 * mean height + 0.4925 * age - 16.6166 * gender + 16.1161_
